# Generated by Django 5.1.5 on 2025-11-26 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='order_status',
            field=models.CharField(choices=[('order_confirmed', 'Order Confirmed'), ('waiting_for_order', 'Waiting for Order'), ('meet_direct', 'Meet Direct'), ('others', 'Others')], default='waiting_for_order', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.AddField(
            model_name='client',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
